This is a heavy commit. Let's see if I can think of everything:
1) Hard dependencies on flex and bison dropped.
2) Circular bison dependency in libphoebe/ resolved.
3) Bison -y now produces C code properly, which means we are
   fully portable (yacc-compliant).
4) make clean and make distclean now leaves f2c'd, flexed and
   bisoned sources alone.
5) make dist in phoebe-lib now includes all sources, including
   the built ones.

diff --git a/phoebe-lib/configure b/phoebe-lib/configure
--- a/phoebe-lib/configure
+++ b/phoebe-lib/configure
@@ -878,7 +878,10 @@ f2c_built_sources
 LEX
 LEX_OUTPUT_ROOT
 LEXLIB
+flex_built_sources
 YACC
+YFLAGS
+bison_built_sources
 HTML_DIR
 PKG_CONFIG
 ENABLE_GTK_DOC_TRUE
@@ -902,7 +905,9 @@ CXXFLAGS
 CCC
 CXXCPP
 F77
-FFLAGS'
+FFLAGS
+YACC
+YFLAGS'
 
 
 # Initialize some variables set by options.
@@ -1518,6 +1523,11 @@ Some influential environment variables:
   CXXCPP      C++ preprocessor
   F77         Fortran 77 compiler command
   FFLAGS      Fortran 77 compiler flags
+  YACC        The `Yet Another C Compiler' implementation to use. Defaults to
+              the first program found out of: `bison -y', `byacc', `yacc'.
+  YFLAGS      The list of arguments that will be passed by default to $YACC.
+              This script will default YFLAGS to the empty string to avoid a
+              default value of `-d' given by some make applications.
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -4385,7 +4395,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4388 "configure"' > conftest.$ac_ext
+  echo '#line 4398 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7116,11 +7126,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7119: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7129: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7123: \$? = $ac_status" >&5
+   echo "$as_me:7133: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7384,11 +7394,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7387: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7397: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7391: \$? = $ac_status" >&5
+   echo "$as_me:7401: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7488,11 +7498,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7491: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7501: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7495: \$? = $ac_status" >&5
+   echo "$as_me:7505: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9785,7 +9795,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9788 "configure"
+#line 9798 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9885,7 +9895,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9888 "configure"
+#line 9898 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12221,11 +12231,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12224: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12234: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12228: \$? = $ac_status" >&5
+   echo "$as_me:12238: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12325,11 +12335,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12328: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12338: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12332: \$? = $ac_status" >&5
+   echo "$as_me:12342: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13886,11 +13896,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13889: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13899: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13893: \$? = $ac_status" >&5
+   echo "$as_me:13903: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13990,11 +14000,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13993: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14003: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13997: \$? = $ac_status" >&5
+   echo "$as_me:14007: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16177,11 +16187,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16180: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16190: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16184: \$? = $ac_status" >&5
+   echo "$as_me:16194: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16445,11 +16455,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16448: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16458: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16452: \$? = $ac_status" >&5
+   echo "$as_me:16462: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16549,11 +16559,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16552: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16562: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16556: \$? = $ac_status" >&5
+   echo "$as_me:16566: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19684,30 +19694,50 @@ fi
 rm -f conftest.l $LEX_OUTPUT_ROOT.c
 
 fi
-    if test "$LEX" != flex -a "$LEX" != flex-new; then
-      echo ""
-      echo "       *** PHOEBE configuration failure ***"
-      echo ""
-      echo "PHOEBE needs the GNU flex 2.5.33 or later to build."
-      echo "Please install it and run ./configure script again."
-      echo ""
-      exit
+    if $LEX --version | grep 2.5.[3-9][0-9] > /dev/null 2>&1; then
+      flex_check_passed="yes"
     fi
 
-    # Check for 2.5.33 version:
-    if ! $LEX --version | grep 2.5.[3-9][0-9] > /dev/null 2>&1; then
-      echo ""
-      echo "       *** PHOEBE configuration failure ***"
-      echo ""
-      echo "PHOEBE needs GNU flex 2.5.33 or later to build."
-      echo "Please install it and run ./configure script again."
-      echo ""
-      exit
-    fi
+  # Check for existence of all flexed sources:
+    flex_built_sources="phoebe_constraints.lex.c phoebe_constraints.lex.h"
+
+
+    flex_missing=""
+    { echo "$as_me:$LINENO: checking for flexed PHOEBE sources" >&5
+echo $ECHO_N "checking for flexed PHOEBE sources... $ECHO_C" >&6; }
+    for f in $flex_built_sources; do
+      test -f libphoebe/$f && found=yes || found=no
+      test "x$found" = "xno" && flex_missing="$flex_missing $f"
+    done
+
+    test -n "$flex_check_passed" && test -n "$flex_missing" && { echo "$as_me:$LINENO: result: no, but may be built" >&5
+echo "${ECHO_T}no, but may be built" >&6; }
+    test -z "$flex_check_passed" && test -n "$flex_missing" && { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+    test -z "$flex_check_passed" && test -n "$flex_missing" && { { echo "$as_me:$LINENO: error:
+    built source file(s) missing in libphoebe/ directory:
+      ${flex_missing}
+
+    The flex program is required to build these source files, but it does
+    not appear to be installed.
+    " >&5
+echo "$as_me: error:
+    built source file(s) missing in libphoebe/ directory:
+      ${flex_missing}
+
+    The flex program is required to build these source files, but it does
+    not appear to be installed.
+    " >&2;}
+   { (exit 1); exit 1; }; }
+
+    test -z "$flex_missing" && { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
 
   # Parser (needed for PHOEBE constraints):
   # (here we don't call AC_PROG_YACC because we don't want -y attached to bison)
-    for ac_prog in 'bison' byacc yacc
+#   AC_CHECK_PROGS(YACC, 'bison' byacc)
+    for ac_prog in 'bison -y' byacc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -19748,18 +19778,45 @@ fi
 
   test -n "$YACC" && break
 done
-test -n "$YACC" || YACC=":"
+test -n "$YACC" || YACC="yacc"
+
+    test -n "$YACC" && bison_check_passed="yes"
+
+  # Check for existence of all bisoned sources:
+    bison_built_sources="phoebe_constraints.tab.c phoebe_constraints.tab.h"
 
 
-    if test "$YACC" == :; then
-      echo ""
-      echo "       *** PHOEBE configuration failure ***"
-      echo ""
-      echo "PHOEBE needs a yacc-compliant grammar parser to build."
-      echo "Please install it and run ./configure script again."
-      echo ""
-      exit
-    fi
+    bison_missing=""
+    { echo "$as_me:$LINENO: checking for bisoned PHOEBE sources" >&5
+echo $ECHO_N "checking for bisoned PHOEBE sources... $ECHO_C" >&6; }
+    for f in $bison_built_sources; do
+      test -f libphoebe/$f && found=yes || found=no
+      test "x$found" = "xno" && bison_missing="$bison_missing $f"
+    done
+
+    test -n "$bison_check_passed" && test -n "$bison_missing" && { echo "$as_me:$LINENO: result: no, but may be built" >&5
+echo "${ECHO_T}no, but may be built" >&6; }
+    test -z "$bison_check_passed" && test -n "$bison_missing" && { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+    test -z "$bison_check_passed" && test -n "$bison_missing" && { { echo "$as_me:$LINENO: error:
+    built source file(s) missing in libphoebe/ directory:
+      ${bison_missing}
+
+    The bison program is required to build these source files, but it does
+    not appear to be installed.
+    " >&5
+echo "$as_me: error:
+    built source file(s) missing in libphoebe/ directory:
+      ${bison_missing}
+
+    The bison program is required to build these source files, but it does
+    not appear to be installed.
+    " >&2;}
+   { (exit 1); exit 1; }; }
+
+    test -z "$bison_missing" && { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
 
   # System type:
 
@@ -22821,7 +22878,10 @@ f2c_built_sources!$f2c_built_sources$ac_delim
 LEX!$LEX$ac_delim
 LEX_OUTPUT_ROOT!$LEX_OUTPUT_ROOT$ac_delim
 LEXLIB!$LEXLIB$ac_delim
+flex_built_sources!$flex_built_sources$ac_delim
 YACC!$YACC$ac_delim
+YFLAGS!$YFLAGS$ac_delim
+bison_built_sources!$bison_built_sources$ac_delim
 HTML_DIR!$HTML_DIR$ac_delim
 PKG_CONFIG!$PKG_CONFIG$ac_delim
 ENABLE_GTK_DOC_TRUE!$ENABLE_GTK_DOC_TRUE$ac_delim
@@ -22832,7 +22892,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 21; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 24; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -23439,9 +23499,6 @@ fi
   echo "-----------------------------------------------------------"
   echo "System type:                      $build"
   echo "C compiler used:                  $CC"
-#  echo "FORTRAN compiler used:            $F77"
-  echo "Grammar lexer used:               $LEX"
-  echo "Grammar parser used:              $YACC"
   echo "PHOEBE library directory:         $prefix/lib"
   echo "PHOEBE include directory:         $prefix/include/phoebe"
   echo "GNU Scientific Library support:   $gslsupport"
@@ -23450,12 +23507,31 @@ fi
   echo "Verbose debugging messages:       $debugstate"
   echo ""
 
-if test -z "$f2c_check_passed"; then
+if test -z "$f2c_check_passed" || test -z "$flex_check_passed"; then
   echo "Notice:"
   echo ""
+fi
+
+if test -z "$f2c_check_passed"; then
   echo "The f2c compiler does not appear to be installed; it is required to"
   echo "rebuild the WD-derived source files that are distributed in this"
   echo "tarball. If you modify FORTRAN sources in libwd/ directory, you will"
   echo "be unable to build PHOEBE without first installing f2c."
+  echo ""
+fi
+
+if test -z "$flex_check_passed"; then
+  echo "Flex 2.5.33 or later does not appear to be installed; it is required"
+  echo "to rebuild PHOEBE lexical source files that are distributed in this"
+  echo "tarball. If you modify the flex sources in libphoebe/ directory, you"
+  echo "will be unable to build PHOEBE without first installing flex."
+  echo ""
+fi
+
+if test -z "$bison_check_passed"; then
+  echo "Bison 1.9 or later does not appear to be installed; it is required"
+  echo "to rebuild PHOEBE grammar source files that are distributed in this"
+  echo "tarball. If you modify the bison sources in libphoebe/ directory, you"
+  echo "will be unable to build PHOEBE without first installing bison."
   echo ""
 fi
