Hard dependency on flex and bison removed from the scripter. The same hacks needed to be done that were done in the library. In adition, several missing build files for make dist have been added to autoconfig directory.

diff --git a/phoebe-scripter/configure b/phoebe-scripter/configure
--- a/phoebe-scripter/configure
+++ b/phoebe-scripter/configure
@@ -696,7 +696,10 @@ am__fastdepCC_FALSE
 LEX
 LEX_OUTPUT_ROOT
 LEXLIB
+flex_built_sources
 YACC
+YFLAGS
+bison_built_sources
 GNUPLOT
 CPP
 GREP
@@ -712,6 +715,8 @@ CFLAGS
 LDFLAGS
 LIBS
 CPPFLAGS
+YACC
+YFLAGS
 CPP'
 
 
@@ -1304,6 +1309,11 @@ Some influential environment variables:
   LIBS        libraries to pass to the linker, e.g. -l<library>
   CPPFLAGS    C/C++/Objective C preprocessor flags, e.g. -I<include dir> if
               you have headers in a nonstandard directory <include dir>
+  YACC        The `Yet Another C Compiler' implementation to use. Defaults to
+              the first program found out of: `bison -y', `byacc', `yacc'.
+  YFLAGS      The list of arguments that will be passed by default to $YACC.
+              This script will default YFLAGS to the empty string to avoid a
+              default value of `-d' given by some make applications.
   CPP         C preprocessor
 
 Use these variables to override the choices made by `configure' or to help
@@ -1747,12 +1757,12 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 # Define the release name, date and type:
 
 cat >>confdefs.h <<\_ACEOF
-#define PHOEBE_SCRIPTER_RELEASE_NAME "PHOEBE scripter 0.30RC1 (release candidate)"
+#define PHOEBE_SCRIPTER_RELEASE_NAME "PHOEBE scripter 0.30RC2 (release candidate)"
 _ACEOF
 
 
 cat >>confdefs.h <<\_ACEOF
-#define PHOEBE_SCRIPTER_RELEASE_DATE "Oct 15, 2007"
+#define PHOEBE_SCRIPTER_RELEASE_DATE "Nov 1, 2007"
 _ACEOF
 
 
@@ -2098,8 +2108,8 @@ fi
 
 
 # Define the identity of the package.
- PACKAGE=phoebe
- VERSION=0.30RC1
+ PACKAGE='phoebe_scripter'
+ VERSION='0.30'
 
 
 cat >>confdefs.h <<_ACEOF
@@ -3577,30 +3587,49 @@ fi
 rm -f conftest.l $LEX_OUTPUT_ROOT.c
 
 fi
-    if test "$LEX" != flex -a "$LEX" != flex-new; then
-      echo ""
-      echo "       *** PHOEBE configuration failure ***"
-      echo ""
-      echo "PHOEBE needs the GNU flex 2.5.33 or later to build."
-      echo "Please install it and run ./configure script again."
-      echo ""
-      exit
+    if $LEX --version | grep 2.5.[3-9][0-9] > /dev/null 2>&1; then
+      flex_check_passed="yes"
     fi
 
-    # Check for 2.5.33 version:
-    if ! $LEX --version | grep 2.5.[3-9][0-9] > /dev/null 2>&1; then
-      echo ""
-      echo "       *** PHOEBE configuration failure ***"
-      echo ""
-      echo "PHOEBE needs GNU flex 2.5.33 or later to build."
-      echo "Please install it and run ./configure script again."
-      echo ""
-      exit
-    fi
+  # Check for existence of all flexed sources:
+    flex_built_sources="phoebe_scripter.lng.c phoebe_scripter.lng.h"
+
+
+    flex_missing=""
+    { echo "$as_me:$LINENO: checking for flexed PHOEBE scripter sources" >&5
+echo $ECHO_N "checking for flexed PHOEBE scripter sources... $ECHO_C" >&6; }
+    for f in $flex_built_sources; do
+      test -f src/$f && found=yes || found=no
+      test "x$found" = "xno" && flex_missing="$flex_missing $f"
+    done
+
+    test -n "$flex_check_passed" && test -n "$flex_missing" && { echo "$as_me:$LINENO: result: no, but may be built" >&5
+echo "${ECHO_T}no, but may be built" >&6; }
+    test -z "$flex_check_passed" && test -n "$flex_missing" && { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+    test -z "$flex_check_passed" && test -n "$flex_missing" && { { echo "$as_me:$LINENO: error:
+    built source file(s) missing in src/ directory:
+      ${flex_missing}
+
+    The flex program is required to build these source files, but it does
+    not appear to be installed.
+  " >&5
+echo "$as_me: error:
+    built source file(s) missing in src/ directory:
+      ${flex_missing}
+
+    The flex program is required to build these source files, but it does
+    not appear to be installed.
+  " >&2;}
+   { (exit 1); exit 1; }; }
+
+  test -z "$flex_missing" && { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
 
   # Parser:
   # (here we don't call AC_PROG_YACC because we don't want -y attached to bison)
-    for ac_prog in 'bison' byacc yacc
+    for ac_prog in 'bison -y' byacc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -3641,18 +3670,45 @@ fi
 
   test -n "$YACC" && break
 done
-test -n "$YACC" || YACC=":"
+test -n "$YACC" || YACC="yacc"
+
+    test -n "$YACC" && bison_check_passed="yes"
+
+  # Check for existence of all bisoned sources:
+    bison_built_sources="phoebe_scripter.grm.c phoebe_scripter.grm.h"
 
 
-    if test "$YACC" == :; then
-      echo ""
-      echo "       *** PHOEBE configuration failure ***"
-      echo ""
-      echo "PHOEBE needs a yacc-compliant grammar parser to build."
-      echo "Please install it and run the ./configure script again."
-      echo ""
-      exit
-    fi
+    bison_missing=""
+    { echo "$as_me:$LINENO: checking for bisoned PHOEBE scripter sources" >&5
+echo $ECHO_N "checking for bisoned PHOEBE scripter sources... $ECHO_C" >&6; }
+    for f in $bison_built_sources; do
+      test -f src/$f && found=yes || found=no
+      test "x$found" = "xno" && bison_missing="$bison_missing $f"
+    done
+
+    test -n "$bison_check_passed" && test -n "$bison_missing" && { echo "$as_me:$LINENO: result: no, but may be built" >&5
+echo "${ECHO_T}no, but may be built" >&6; }
+    test -z "$bison_check_passed" && test -n "$bison_missing" && { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+    test -z "$bison_check_passed" && test -n "$bison_missing" && { { echo "$as_me:$LINENO: error:
+    built source file(s) missing in src/ directory:
+      ${bison_missing}
+
+    The bison program is required to build these source files, but it does
+    not appear to be installed.
+    " >&5
+echo "$as_me: error:
+    built source file(s) missing in src/ directory:
+      ${bison_missing}
+
+    The bison program is required to build these source files, but it does
+    not appear to be installed.
+    " >&2;}
+   { (exit 1); exit 1; }; }
+
+    test -z "$bison_missing" && { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
 
 # Check if PHOEBE library is installed:
 
@@ -6920,7 +6976,10 @@ am__fastdepCC_FALSE!$am__fastdepCC_FALSE$ac_delim
 LEX!$LEX$ac_delim
 LEX_OUTPUT_ROOT!$LEX_OUTPUT_ROOT$ac_delim
 LEXLIB!$LEXLIB$ac_delim
+flex_built_sources!$flex_built_sources$ac_delim
 YACC!$YACC$ac_delim
+YFLAGS!$YFLAGS$ac_delim
+bison_built_sources!$bison_built_sources$ac_delim
 GNUPLOT!$GNUPLOT$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
@@ -6929,7 +6988,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 88; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 91; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -7535,8 +7594,7 @@ fi
   echo "Configuration summary for $PACKAGE_STRING:"
   echo "-----------------------------------------------------------------"
   echo "C compiler used:                  $CC"
-  echo "Grammar lexer used:               $LEX"
-  echo "Grammar parser used:              $YACC"
+  echo "Maintainer mode (build sources):  $USE_MAINTAINER_MODE"
   echo "Top-level install directory:      $prefix"
   echo "Scripter binary goes to:          $prefix/bin"
   echo "Scripter help files go to:        $prefix/share/phoebe_scripter"
@@ -7544,3 +7602,24 @@ fi
   echo "GNU readline library present:     $readlinesupport"
   echo "Verbose debugging messages:       $debugstate"
   echo ""
+
+if test -z "$flex_check_passed" || test -z "$bison_check_passed"; then
+  echo "Notice:"
+  echo ""
+fi
+
+if test -z "$flex_check_passed"; then
+  echo "Flex 2.5.33 or later does not appear to be installed; it is required"
+  echo "to rebuild PHOEBE lexical source files that are distributed in this"
+  echo "tarball. If you modify the flex sources in the src/ directory, you"
+  echo "will be unable to build PHOEBE without first installing flex."
+  echo ""
+fi
+
+if test -z "$bison_check_passed"; then
+  echo "Bison 1.9 or later does not appear to be installed; it is required"
+  echo "to rebuild PHOEBE grammar source files that are distributed in this"
+  echo "tarball. If you modify the bison sources in the src/ directory, you"
+  echo "will be unable to build PHOEBE without first installing bison."
+  echo ""
+fi
