Build files updated to work without f2c, flex or bison if the source files are present (i.e. from a distribution tarball, but not from SVN). Hopefully this commit resolves all remaining problems with the missing f2c.

diff --git a/devel/phoebe-lib/configure b/devel/phoebe-lib/configure
--- a/devel/phoebe-lib/configure
+++ b/devel/phoebe-lib/configure
@@ -19624,52 +19624,6 @@ fi
 
 
 
-  # Check for existence of all built WD and WD-related sources:
-    f2c_built_sources="                      \
-      atmx.c      bbl.c      binnum.c cloud.c  conjph.c  \
-      dc.sub.c    dgmprd.c   dminv.c  dura.c   ellone.c  \
-      fourls.c    gabs.c     jdph.c   kepler.c lcr.c     \
-      lc.sub.c    legendre.c light.c  linpro.c lum.c     \
-      lump.c      mlrg.c     modlog.c nekmin.c olump.c   \
-      planckint.c rangau.c   ranuni.c rddata.c ring.c    \
-      romq.c      sincos.c   spot.c   square.c surfas.c  \
-      volume.c    wrdata.c   wrdci.c  wrfoot.c wrhead.c  \
-      wrlci.c"
-
-
-
-    f2c_missing=""
-    { echo "$as_me:$LINENO: checking for WD sources built with f2c" >&5
-echo $ECHO_N "checking for WD sources built with f2c... $ECHO_C" >&6; }
-    for f in $f2c_built_sources; do
-      test -f libwd/$f && found=yes || found=no
-      test "x$found" = "xno" && f2c_missing="$f2c_missing $f"
-    done
-
-    test -n "$f2c_check_passed" && test -n "$f2c_missing" && { echo "$as_me:$LINENO: result: no, but may be built" >&5
-echo "${ECHO_T}no, but may be built" >&6; }
-    test -z "$f2c_check_passed" && test -n "$f2c_missing" && { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-
-    test -z "$f2c_check_passed" && test -n "$f2c_missing" && { { echo "$as_me:$LINENO: error:
-    built source file(s) missing in libwd/ directory:
-      ${f2c_missing}
-
-    The f2c program is required to build these source files, but it does
-    not appear to be installed.
-    " >&5
-echo "$as_me: error:
-    built source file(s) missing in libwd/ directory:
-      ${f2c_missing}
-
-    The f2c program is required to build these source files, but it does
-    not appear to be installed.
-    " >&2;}
-   { (exit 1); exit 1; }; }
-
-    test -z "$f2c_missing" && { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-
   # g2c library:
     g2c_check_passed=yes
 
@@ -19748,6 +19702,52 @@ fi
       echo ""
       exit
     fi
+
+  # Check for existence of all built WD and WD-related sources:
+    f2c_built_sources="                      \
+      atmx.c      bbl.c      binnum.c cloud.c  conjph.c  \
+      dc.sub.c    dgmprd.c   dminv.c  dura.c   ellone.c  \
+      fourls.c    gabs.c     jdph.c   kepler.c lcr.c     \
+      lc.sub.c    legendre.c light.c  linpro.c lum.c     \
+      lump.c      mlrg.c     modlog.c nekmin.c olump.c   \
+      planckint.c rangau.c   ranuni.c rddata.c ring.c    \
+      romq.c      sincos.c   spot.c   square.c surfas.c  \
+      volume.c    wrdata.c   wrdci.c  wrfoot.c wrhead.c  \
+      wrlci.c"
+
+
+
+    f2c_missing=""
+    { echo "$as_me:$LINENO: checking for WD sources built with f2c" >&5
+echo $ECHO_N "checking for WD sources built with f2c... $ECHO_C" >&6; }
+    for f in $f2c_built_sources; do
+      test -f libwd/$f && found=yes || found=no
+      test "x$found" = "xno" && f2c_missing="$f2c_missing $f"
+    done
+
+    test -n "$f2c_check_passed" && test -n "$f2c_missing" && { echo "$as_me:$LINENO: result: no, but may be built" >&5
+echo "${ECHO_T}no, but may be built" >&6; }
+    test -z "$f2c_check_passed" && test -n "$f2c_missing" && { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+    test -z "$f2c_check_passed" && test -n "$f2c_missing" && { { echo "$as_me:$LINENO: error:
+    built source file(s) missing in libwd/ directory:
+      ${f2c_missing}
+
+    The f2c program is required to build these source files, but it does
+    not appear to be installed.
+    " >&5
+echo "$as_me: error:
+    built source file(s) missing in libwd/ directory:
+      ${f2c_missing}
+
+    The f2c program is required to build these source files, but it does
+    not appear to be installed.
+    " >&2;}
+   { (exit 1); exit 1; }; }
+
+    test -z "$f2c_missing" && { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
 
   # Lexer (needed for PHOEBE constraints); we require flex 2.5.33 or later:
     for ac_prog in flex lex
@@ -19995,7 +19995,6 @@ echo "$as_me: error:
 echo "${ECHO_T}yes" >&6; }
 
   # Parser (needed for PHOEBE constraints):
-  # (here we don't call AC_PROG_YACC because we don't want -y attached to bison)
     for ac_prog in 'bison -y' byacc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
